version: '2'

services:
  web:
      image: nginx:latest
      volumes:
          - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
          - ./app:/app

  php:
      image: php:fpm
      volumes:
          - ./app:/app

  myapp:
    image: bitnami/symfony:4.4
    ports:
      - '80:8000'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=bn_myapp
      - SYMFONY_DATABASE_NAME=bitnami_myapp
    volumes:
      - './my-project:/app'
